- network/base/views.py
- network/templates/account/login.html
> Exclude Satellites with no Transponders

- Dockerfile
- fig.yml
- requirements/docker.txt
This way the development environment will be closer to production.
> Use MariaDB for docker

- network/base/admin.py
> Fix to allow uploading payloads through /admin/

- network/templates/base/station_view.html
- network/templates/base/stations.html
> Fix Ground Station table overflow when QTH present.

- network/base/views.py
- network/templates/base/station_view.html
> Next satellites to pass for station view

- network/templates/avatar/change.html
> Fix avatar wrong template tag

- network/templates/base/observations.html
> Choose blue color for upcoming observations

- network/static/js/observation_new.js
- network/static/js/observation_view.js
- network/templates/base.html
* Timeline svg should adapt on screen width (Fixes #206)
* Top menu fix for small screens
> Fix responsive UI issues

- network/base/helpers.py
- network/base/management/commands/initialize.py
- network/base/tests.py
> Use only Satellites with Transmitters on fixtures

- network/settings/base.py
- network/users/models.py
Did you want global pagination or per API view pagination?
> Fixes #95 Added pagination to settings

- .gitignore
- .idea/vcs.xml
Found I'd accidentally added this IDE file to git in my first pull request (sorry, rookie mistake).
> Remove Pycharm IDE project file and add to gitignore

- .stylelintrc
- .travis.yml
- network/static/css/app.css
- requirements/base.txt
- requirements/dev.txt
> Add stylelint

- network/base/models.py
- network/static/css/app.css
- network/templates/base/observation_view.html
Obs view refactor with tabs and cleanup of buttons
> Rearrange data view in observation view with tabs.

- network/static/js/observation_view.js
- network/templates/base/observation_view.html
> [Fixes #307] Add unique id for "Loading data" notice on audio tabs

- network/static/css/app.css
Tiny fix of color for label-warning
> Fix color of label-warning for colorblindness ease.

- network/static/js/observation_view.js
- network/templates/base/observation_view.html
This pull request contains two commits, one for addition of progress bar and one for spectrogram generation.
It should be merged after pull request #309.
> Add progress bar and spectrogram on audio tab

- .eslintignore
- .jshintignore
- Dockerfile
- docker-compose.yml
- docker/run-common.sh
- docker/run-compose.sh
- docker/run-docker.sh
- network/base/context_processors.py
- network/base/views.py
- network/settings/base.py
- network/settings/docker.py
- network/settings/production.py
- network/settings/stage.py
- network/static/js/app.js
- network/static/js/dnt-helper.js
- network/static/js/ga.js
- network/static/js/home.js
- network/static/js/station_view.js
- network/templates/base.html
- network/templates/base/home.html
- network/templates/base/station_view.html
- network/templates/includes/analytics.html
- requirements/base.txt
- requirements/dev.txt
- requirements/docker.txt
- requirements/production.txt
* CSP support (fixes #282)
* Add redis cache support
* Use hashes for pip
* Simplify GA code
> Several enhancements

- network/base/views.py
Model properties cannot be filtered by SQL, now using  some annotated fields with aggregation functions.
Tested this on my dev box with 8000 observations, page load went from 15sec to 440ms so I think I'm on the right track here.
> [Fixes #315] Use query annotation instead of model properties to filter Observation faster

- network/base/helpers.py
- network/base/views.py
- network/static/js/station_view.js
- network/templates/base/station_view.html
> Polar plot

- network/base/fixtures/antennas.json
Model was updated but not the fixtures for test/dev
> Added frequency_max to fixtures so initialize will work

- .travis.yml
- network/static/js/app.js
- network/static/js/observation_view.js
- network/static/js/station_view.js
- network/templates/base/home.html
- network/templates/base/observations.html
- network/templates/base/station_view.html
* Show stations involved on observation lists
* Show recent observations on station view
> Stations enhancements
